apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: ebookshop

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:17

          command:
            - sh
            - -c
            - |
              until pg_isready -h postgres-service -p 5432 -U emtlab
              do
                echo "Waiting for PostgreSQL..."
                sleep 2
              done

      containers:
        - name: backend

          image: emaf025/e-bookshop-backend:latest

          ports:
            - containerPort: 8080

          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: JWT_SECRET_KEY