spring.datasource.url=jdbc:postgresql://localhost:5433/emtlab
spring.datasource.username=emtlab
spring.datasource.password=emtlab

spring.jpa.hibernate.ddl-auto=validate

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE


#spring.jpa.show-sql=true
#
#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration
