spring.application.name=EMTlab

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

#server.port=8080

#jwt.secret=${JWT_SECRET_KEY}
jwt.secret=pTWVqDLYX63sUNCFvHLNImsqTDXIhNbEIyRtE0rjcDs=
jwt.expiration=864000000
jwt.header=Authorization
jwt.token-prefix=Bearer

# comes from environment
# token validity (10 days)
# HTTP header name
# prefix in header

spring.profiles.active=dev