spring.application.name=EMTlab

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

jwt.secret=${JWT_SECRET_KEY:pTWVqDLYX63sUNCFvHLNImsqTDXIhNbEIyRtE0rjcDs=}
jwt.expiration=864000000
jwt.header=Authorization
jwt.token-prefix=Bearer

spring.profiles.active=dev