#spring.datasource.url=jdbc:postgresql://localhost:5433/emtlab
#spring.datasource.username=emtlab
#spring.datasource.password=emtlab

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/emtlab}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:emtlab}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:emtlab}

spring.jpa.hibernate.ddl-auto=validate

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

